### ISSUE TITLE
When I search for events happening in Europe, non European countries are mentioned

### ISSUE THREAD

**Issue by rainbowbreeze** [kevinsimper/gdg-search#51]
https://gdgsearch.com/#!upcoming?region=Europe

As per screenshot, Uganda, Singapore and other countries are in the list
![Screenshot 2020-04-16 at 09 59 35](https://user-images.githubusercontent.com/381940/79430311-0bb84080-7fc9-11ea-988a-34f36a3bc53a.png)

**Comment by kevinsimper** [comment]
Hi Alfredo,

Thanks for the screenshot!

I found the same mistake and I think the problem is this: https://github.com/kevinsimper/gdg-search/issues/49

When the first request is slower (the whole world) than the request when it figures out the region (europe, many fewer events) loads quicker.

Solution is cancel any request already happening before starting a new request. https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

**Comment by kevinsimper** [comment]
There is a bug where "Russia" appears in the europe filter even after first load is not a problem.
